DROP TABLE IF EXISTS "comments";
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS "columns";
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS memberships;
DROP TYPE IF EXISTS ROLE;
DROP EXTENSION IF EXISTS "uuid-ossp";
