// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Publisher is an autogenerated mock type for the publisher type
type Publisher struct {
	mock.Mock
}

// Publish provides a mock function with given fields: subject, message
func (_m *Publisher) Publish(subject string, message []byte) {
	_m.Called(subject, message)
}

type NewPublisherT interface {
	mock.TestingT
	Cleanup(func())
}

// NewPublisher creates a new instance of Publisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPublisher(t NewPublisherT) *Publisher {
	mock := &Publisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
