// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	database "github.com/devpies/devpie-client-core/users/platform/database"
	mock "github.com/stretchr/testify/mock"

	time "time"

	users "github.com/devpies/devpie-client-core/users/domain/users"
)

// UserQuerier is an autogenerated mock type for the UserQuerier type
type UserQuerier struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, repo, nu, aid, now
func (_m *UserQuerier) Create(ctx context.Context, repo *database.Repository, nu users.NewUser, aid string, now time.Time) (users.User, error) {
	ret := _m.Called(ctx, repo, nu, aid, now)

	var r0 users.User
	if rf, ok := ret.Get(0).(func(context.Context, *database.Repository, users.NewUser, string, time.Time) users.User); ok {
		r0 = rf(ctx, repo, nu, aid, now)
	} else {
		r0 = ret.Get(0).(users.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *database.Repository, users.NewUser, string, time.Time) error); ok {
		r1 = rf(ctx, repo, nu, aid, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetrieveByEmail provides a mock function with given fields: repo, email
func (_m *UserQuerier) RetrieveByEmail(repo *database.Repository, email string) (users.User, error) {
	ret := _m.Called(repo, email)

	var r0 users.User
	if rf, ok := ret.Get(0).(func(*database.Repository, string) users.User); ok {
		r0 = rf(repo, email)
	} else {
		r0 = ret.Get(0).(users.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*database.Repository, string) error); ok {
		r1 = rf(repo, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetrieveMe provides a mock function with given fields: ctx, repo, uid
func (_m *UserQuerier) RetrieveMe(ctx context.Context, repo *database.Repository, uid string) (users.User, error) {
	ret := _m.Called(ctx, repo, uid)

	var r0 users.User
	if rf, ok := ret.Get(0).(func(context.Context, *database.Repository, string) users.User); ok {
		r0 = rf(ctx, repo, uid)
	} else {
		r0 = ret.Get(0).(users.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *database.Repository, string) error); ok {
		r1 = rf(ctx, repo, uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetrieveMeByAuthID provides a mock function with given fields: ctx, repo, aid
func (_m *UserQuerier) RetrieveMeByAuthID(ctx context.Context, repo *database.Repository, aid string) (users.User, error) {
	ret := _m.Called(ctx, repo, aid)

	var r0 users.User
	if rf, ok := ret.Get(0).(func(context.Context, *database.Repository, string) users.User); ok {
		r0 = rf(ctx, repo, aid)
	} else {
		r0 = ret.Get(0).(users.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *database.Repository, string) error); ok {
		r1 = rf(ctx, repo, aid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
