// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/devpies/saas-core/internal/project/model"

	time "time"
)

// ProjectService is an autogenerated mock type for the projectService type
type ProjectService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, project, now
func (_m *ProjectService) Create(ctx context.Context, project model.NewProject, now time.Time) (model.Project, error) {
	ret := _m.Called(ctx, project, now)

	var r0 model.Project
	if rf, ok := ret.Get(0).(func(context.Context, model.NewProject, time.Time) model.Project); ok {
		r0 = rf(ctx, project, now)
	} else {
		r0 = ret.Get(0).(model.Project)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.NewProject, time.Time) error); ok {
		r1 = rf(ctx, project, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, projectID
func (_m *ProjectService) Delete(ctx context.Context, projectID string) error {
	ret := _m.Called(ctx, projectID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, projectID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: ctx, all
func (_m *ProjectService) List(ctx context.Context, all bool) ([]model.Project, error) {
	ret := _m.Called(ctx, all)

	var r0 []model.Project
	if rf, ok := ret.Get(0).(func(context.Context, bool) []model.Project); ok {
		r0 = rf(ctx, all)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Project)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, bool) error); ok {
		r1 = rf(ctx, all)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Retrieve provides a mock function with given fields: ctx, projectID
func (_m *ProjectService) Retrieve(ctx context.Context, projectID string) (model.Project, error) {
	ret := _m.Called(ctx, projectID)

	var r0 model.Project
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Project); ok {
		r0 = rf(ctx, projectID)
	} else {
		r0 = ret.Get(0).(model.Project)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, projectID, update, now
func (_m *ProjectService) Update(ctx context.Context, projectID string, update model.UpdateProject, now time.Time) (model.Project, error) {
	ret := _m.Called(ctx, projectID, update, now)

	var r0 model.Project
	if rf, ok := ret.Get(0).(func(context.Context, string, model.UpdateProject, time.Time) model.Project); ok {
		r0 = rf(ctx, projectID, update, now)
	} else {
		r0 = ret.Get(0).(model.Project)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, model.UpdateProject, time.Time) error); ok {
		r1 = rf(ctx, projectID, update, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type NewProjectServiceT interface {
	mock.TestingT
	Cleanup(func())
}

// NewProjectService creates a new instance of ProjectService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProjectService(t NewProjectServiceT) *ProjectService {
	mock := &ProjectService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
