apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-identity-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-identity
  template:
    metadata:
      labels:
        app: app-identity
    spec:
      containers:
        - image: devpies/client-app-identity
          name: app-identity
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "250m"
              memory: "250Mi"
          env:
            - name: APP_NAME
              value: Identity
            - name: NODE_ENV
              value: development
            - name: PORT
              value: "4000"
            - name: TIMEZONE
              value: "Europe/Berlin"
            - name: NATS_SERVER
              value: "http://nats-svc:4222"
            - name: CLUSTER_ID
              value: "devpie-client"
            - name: CLIENT_ID
              value: app-identity
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: view-db-identity-url
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: auth0-domain
            - name: AUTH0_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: auth0-audience
      initContainers:
        - name: schema-migration
          image: devpies/view-db-identity-migration:v000002
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: view-db-identity-url
          command: ["migrate"]
          args:
            ["-path", "/migrations", "-verbose", "-database", "$(DB_URL)", "up"]
---
apiVersion: v1
kind: Service
metadata:
  name: app-identity-svc
spec:
  selector:
    app: app-identity
  ports:
    - name: app-identity
      port: 4000
      targetPort: 4000
