// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/devpies/saas-core/internal/admin/model"

	web "github.com/devpies/saas-core/pkg/web"
)

// RegistrationService is an autogenerated mock type for the registrationService type
type RegistrationService struct {
	mock.Mock
}

// RegisterTenant provides a mock function with given fields: ctx, tenant
func (_m *RegistrationService) RegisterTenant(ctx context.Context, tenant model.NewTenant) (*web.ErrorResponse, int, error) {
	ret := _m.Called(ctx, tenant)

	var r0 *web.ErrorResponse
	if rf, ok := ret.Get(0).(func(context.Context, model.NewTenant) *web.ErrorResponse); ok {
		r0 = rf(ctx, tenant)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*web.ErrorResponse)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(context.Context, model.NewTenant) int); ok {
		r1 = rf(ctx, tenant)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, model.NewTenant) error); ok {
		r2 = rf(ctx, tenant)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

type NewRegistrationServiceT interface {
	mock.TestingT
	Cleanup(func())
}

// NewRegistrationService creates a new instance of RegistrationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRegistrationService(t NewRegistrationServiceT) *RegistrationService {
	mock := &RegistrationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
